backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"  # Netlify 托管时不需要项目前缀

collections:
  - name: "posts"
    label: "文章"
    label_singular: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "标签", name: "tags", widget: "list", default: [] }
      - { label: "摘要", name: "excerpt", widget: "text" }
      - {
          label: "头图",
          name: "heroImage",
          widget: "image",
          allow_multiple: false
        }
      - { label: "草稿", name: "draft", widget: "boolean", default: false }
      - { label: "正文", name: "body", widget: "markdown" }